version: '3.8'

services:
  api-service:
    container_name: espada-api-prod
    build:
      context: ./
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - '8080:8080'
    networks:
      - nqt-network

networks:
  nqt-network:
    external: true