server:
  port: ${SERVER-PORT}
  servlet:
    context-path: ${CONTEXT-PATH}

client:
  home-page: ${CLIENT-HOME-PAGE:"http://localhost:3000"}
  verification-success-page: ${CLIENT-VERIFICATION-SUCCESS-PAGE:"http://localhost:3000/verification-success"}
  order-page: ${CLIENT-ORDER-PAGE:"http://localhost:3000/my-order"}

spring:
  application:
    name: espada-backend-service
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: ${DB-URL}
    driverClassName: ${DB-DRIVER-CLASSNAME:"com.mysql.cj.jdbc.Driver"}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  jpa:
    show-sql: true
  mail:
    host: ${MAIL-HOST}
    port: ${MAIL-PORT}
    username: ${MAIL-USERNAME}
    password: ${MAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  task:
    scheduling:
      pool:
        size: ${TASK-SCHEDULING-POOL-SIZE:3}

jwt:
  signerKey: ${JWT-SIGNER-KEY}
  refreshSignerKey: ${JWT-REFRESH-SIGNER-KEY}
  valid-duration: ${JWT-VALID-DURATION} # in second
  refreshable-duration: ${JWT-REFRESHABLE-DURATION} # in second

verify-code:
  valid-duration: ${VERIFY-CODE-DURATION} # in second

payment:
  vnpay:
    version: ${VNP-VERSION:2.1.0}
    vnp_command: ${VNPAY-COMMAND}
    tmn-code: ${VNPAY-TMN-CODE}
    secret-key: ${VNPAY-SECRET-KEY}
    payment-url: ${VNPAY-PAYMENT-URL}
    return-url: ${VNPAY-RETURN-URL}
    orderType: ${VNPAY-ORDER-TYPE}
    success-code: ${VNPAY-SUCCESS-CODE}

initial-admin-account:
  id: "admin"
  username: "admin"
  password: "admin123"
  email: "admin@admin.com"
  phoneNumber: "0123456789"
  role: "ADMIN"
  firstName: "Admin"
  lastName: "Admin"

page-size-default:
  product: 12
  best-seller: 8
  you-may-like: 4

success-request-code: 1000
