server:
  port: 8080
  servlet:
    context-path: /api

client:
  home-page: "http://localhost:3000"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/espada_store"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nqt460@gmail.com
    password: "rjkb ygqs qpur gqut"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  task:
    scheduling:
      pool:
        size: 3

jwt:
  signerKey: "GF8bIi7ezOnrdsZvh1gt1sHc5E8KnJaybTf88q5GecpO4E6NhR0PENFaBM+ZEyVG"
  refreshSignerKey: "7+78pvfH7Pp4WK8py2tecwSfH+Cvt56WKuWNEDOmqsEaiDwjWh2wBI56+gTMMy9S"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second

page-size-default:
  product: 12
  best-seller: 8

verify-code:
  valid-duration: 300 # in second

success-request-code: 1000

payment:
  vnpay:
    version: 2.1.0
    vnp_command: "pay"
    tmn-code: "UA43J0W0"
    secret-key: "ZAXWF5MTGRNIU2JE497F8PSNQOZ06YVK"
    payment-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    return-url: "http://localhost:8080/api/payment/vnpay/vnpay-return"
    orderType: "other"
    success-code: "00"
