server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/espada_store"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nqt460@gmail.com
    password: "rjkb ygqs qpur gqut"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "GF8bIi7ezOnrdsZvh1gt1sHc5E8KnJaybTf88q5GecpO4E6NhR0PENFaBM+ZEyVG"
  refreshSignerKey: "7+78pvfH7Pp4WK8py2tecwSfH+Cvt56WKuWNEDOmqsEaiDwjWh2wBI56+gTMMy9S"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second

page-size-default:
  product: 12

verify-code:
  valid-duration: 300 # in second

success-request-code: 1000

order:
  state:
    waiting-confirm: "waiting-confirm"
    preparing: "preparing"
    shipping: "shipping"
    to-customer: "to-customer"
    delivered: "delivered"
